# Generated by Django 4.2.2 on 2023-07-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_venue_venue_image_alter_venue_email_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="email_address",
            field=models.EmailField(max_length=254, verbose_name="Email Address"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="phone",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="venue",
            name="web",
            field=models.URLField(verbose_name="Website Address"),
        ),
    ]
