# Generated by Django 4.2.2 on 2023-07-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_venue_email_address_alter_venue_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="venue_image",
        ),
        migrations.AlterField(
            model_name="venue",
            name="email_address",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="venue",
            name="web",
            field=models.URLField(blank=True, verbose_name="Website Address"),
        ),
    ]
